[book]
authors = ["Silen Locatelli"]
language = "en"
multilingual = false
src = "src"
title = "My Wishlist"
description = "A curated list of things I'd love to have"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = ["assets/css/custom.css"]
git-repository-url = "https://github.com/silen/wishlist"
git-repository-icon = "fa-github"

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
